//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eYillik
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_BestTeacher
    {
        public int BestId { get; set; }
        public string BestName { get; set; }
        public string BestTeacher { get; set; }
        public Nullable<byte> BestOrderBy { get; set; }
    }
}
