//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eYillik
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_Remembers
    {
        public int RememberID { get; set; }
        public Nullable<System.Guid> ToUser { get; set; }
        public Nullable<System.Guid> FromUser { get; set; }
        public string RememberContent { get; set; }
    
        public virtual sys_Users sys_Users { get; set; }
        public virtual sys_Users sys_Users1 { get; set; }
    }
}
