//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eYillik
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_Pictures
    {
        public int PictureID { get; set; }
        public string PicturePath { get; set; }
        public string AlbumName { get; set; }
    
        public virtual sys_Album sys_Album { get; set; }
    }
}
