//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eYillik
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_Users
    {
        public sys_Users()
        {
            this.sys_Remembers = new HashSet<sys_Remembers>();
            this.sys_Remembers1 = new HashSet<sys_Remembers>();
        }
    
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string UserSurname { get; set; }
        public string UserPicture { get; set; }
        public string UserFacebook { get; set; }
        public string UserTwitter { get; set; }
        public string UserLinkedin { get; set; }
        public string UserGooglePlus { get; set; }
        public string UserGithub { get; set; }
        public string UserPinterest { get; set; }
        public string UserPersonal { get; set; }
        public string UserRetry { get; set; }
        public string UserRecommend { get; set; }
        public string UserFriend { get; set; }
        public string UserNumber { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<sys_Remembers> sys_Remembers { get; set; }
        public virtual ICollection<sys_Remembers> sys_Remembers1 { get; set; }
    }
}
